basePath: /
definitions:
  controllers.errorResponse:
    properties:
      errorMessage:
        type: string
      statusCode:
        type: integer
    type: object
  controllers.response:
    properties:
      auth_token:
        type: string
    type: object
host: localhost:3003
info:
  contact:
    email: nikolaevforbuss@gmail.com
    name: Nikolaev Yakov
  description: This is a service for generating authentication tokens and their refresh
  title: Authentication Service
  version: "1.0"
paths:
  /auth/generateTokens:
    get:
      description: Generate tokens by guid in query
      parameters:
      - description: guid
        in: query
        name: guid
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: GenerateTokens
      tags:
      - auth
  /auth/refresh:
    get:
      description: Refresh tokens by given valid 'refresh token' in cookies
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/controllers.response'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/controllers.errorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/controllers.errorResponse'
      summary: RefreshTokens
      tags:
      - auth
swagger: "2.0"
